# upload and mount an iso
# vars:
# - iso.src: local source for upload 
# - iso.dest: remote destination path
# - iso.mount_path: remote mount path
- name: upload an ISO
  action: copy
    src=${iso.src}
    dest=${iso.dest}
    owner=root
    group=root
    mode=0644
  when: "iso.src is defined"
  when: "iso.dest is defined"
  tags:
  - iso
  - iso_upload

- name: create mount dir
  action: file
    path=${iso.mount_path}
    state=directory
  when: "iso.mount_path is defined"
  tags:
  - iso
  - iso_create_mount_dir

# TODO: this is a remount; there might be a better way...
- name: re-mount iso; mount
  action: mount
    name=${iso.mount_path}
    src=${iso.dest}
    fstype=iso9660
    state=mounted
    opts=loop
  when: "iso.mount_path is defined"
  tags:
  - iso
  - iso_mount

- name: re-mount iso; umount
  action: mount
    name=${iso.mount_path}
    src=${iso.dest}
    fstype=iso9660
    state=unmounted
    opts=loop
  when: "iso.mount_path is defined"
  tags:
  - iso
  - iso_mount

- name: re-mount iso; mount again
  action: mount
    name=${iso.mount_path}
    src=${iso.dest}
    fstype=iso9660
    state=mounted
    opts=loop
  when: "iso.mount_path is defined"
  tags:
  - iso
  - iso_mount
