# handle a rhn_channel
# based on variables
- name: rhn_channel
  action: rhn_channel
    name=${rhn.channel}
    sysname=${rhn.sysname}
    url=${rhn.url}
    user=${rhn.user}
    password=${rhn.password}
    state=${rhn.state}
  when: "rhn.channel is defined"
  when: "rhn.sysname is defined"
  when: "rhn.url is defined"
  when: "rhn.user is defined"
  when: "rhn.password is defined"
  when: "rhn.state is defined"
