- name: create user SSH key pair
  action: shell ssh-keygen -f ${ssh_keys_file} -t rsa -N "" -P ""
    creates=${ssh_keys_file}
  register: _ssh_keygen_status
  tags:
  - ssh_keygen
  when: "ssh_keys_file is defined"

- name: restore SELinux for ssh key pair
  shell: |
    restorecon -R `dirname ${ssh_keys_file}`
  when: _ssh_keygen_status.changed
  tags:
  - ssh_keygen
  - restorecon

- name: fetch public part of the key pair
  action: fetch
    src=${ssh_keys_file}.pub
    dest=${ssh_keys_top_dir}
  when: "ssh_keys_top_dir is defined and ssh_keys_file is defined"
  tags:
  - ssh_keygen
  - fetch_pub_cert

