# requires ssh_keys_host and ssh_keys_file to operate
# ssh ssh_keygen tasks have to run before
# schema:
#  ssh_keys_host/ssh_keys_file.pub -> ansible_user_id@ansible_hostname:~ssh_authorized_keys_user/ssh_authorized_keys_file

- name: authorize an ssh key for a user and a role
  action: authorized_key
    key="${item}"
    user=${ssh_authorized_keys_user}
    path=${ssh_authorized_keys_file}
    state=present
  when: "ssh_authorized_keys_file is defined"
  when: "ssh_authorized_keys_hardening is not defined"
  with_file:
  - ${ssh_keys_top_dir}/${ssh_keys_host}/${ssh_keys_file}.pub
  tags:
  - ssh_authorize_key

- name: authorize and harden an ssh key for a user and a role
  action: authorized_key
    key='${ssh_authorized_keys_hardening} ${item}'
    user=${ansible_user_id}
    path=${ssh_authorized_keys_file}
    state=present
  when: "ssh_authorized_keys_file is defined"
  when: "ssh_authorized_keys_hardening is defined"
  with_file:
  - ${ssh_keys_top_dir}/${ssh_keys_host}/${ssh_keys_file}.pub
  tags:
  - ssh_authorize_key

