# common storage tasks
- name: get storage devices
  # this shall return the largest non-mounted disk (partition)
  action: shell find /dev -name "xvd*" -not -exec grep -q {} /proc/mounts \; -printf "%p~" -exec sfdisk -suM {} \; | sort  -n | tail -1 | cut -d~ -f1\,1 | xargs -I {} basename {} | tee /tmp/storage_${storage.name}.flag
    creates=/tmp/storage_${storage.name}.flag
  register: disk
  when: "storage.name is defined"
  tags:
  - storage
  - storage_disk

- name: mkfs.ext4 on disk
  action: shell /sbin/mkfs.ext4 /dev/${disk.stdout_lines[0]} && touch /tmp/${disk.stdout_lines[0]}.mkfs.flag
    creates=/tmp/${disk.stdout_lines[0]}.mkfs.flag
  async: 900
  poll: 10
  when: "disk is defined"
  tags:
  - storage
  - storage_mkfs

- name: create storage directory mount path
  action: file
      path=${storage.mount_path}
      state=directory
  when: "storage.mount_path is defined"
  tags:
  - storage
  - storage_mount_path

- name: mount disk
  action: mount
      name=${storage.mount_path}
      src=/dev/${disk.stdout_lines[0]}
      fstype=ext4
      state=mounted
  when: "disk is defined"
  when: "storage.mount_path is defined"
  tags:
  - storage
  - storage_mount

- name: correct storage directory permissions
  action: file
      path=${storage.mount_path}
      state=directory
      owner=${storage.owner}
      group=${storage.group}
      mode=${storage.mode}
  when: "storage.mount_path is defined"
  when: "storage.owner is defined"
  when: "storage.group is defined"
  when: "storage.mode is defined"
  tags:
  - storage
  - storage_permissions
