# stuff common to masters setup
# mostly tools
- name: install packages
  action: yum name=${item} state=installed
  tags:
  - common_master_packages
  - install_packages
  with_items:
  - git
  - make
  - vim
  - ipython
  - PyYAML
  - python-paramiko
  - python-jinja2
  - python-setuptools
  - python-devel
  - python-requests
  - python-iso8601
  - asciidoc
  - rpm-build
  - python-nose
  - pymongo
  - "https://rhuiqerpm.s3.amazonaws.com/python-plumbum-1.1.0_gitebe4cc4-2.fc18.noarch.rpm"
  - "https://rhuiqerpm.s3.amazonaws.com/python-rpyc-3.3.0git40daa0c6-2.fc18.noarch.rpm"
  - "https://rhuiqerpm.s3.amazonaws.com/python-selenium-2.33.1-1.git.1.ad541f1.fc19.x86_64.rpm"

- name: easy install packages
  action: easy_install name=${item}
  tags:
  - common_master_packages
  - easy_install_packages
  with_items:
  - "http://darcs.idyll.org/~t/projects/pinocchio-latest.tar.gz"


