# SAM & SATELLITE INSTALLER
- include: satellite-installer.yml
- include: splice-installer.yml

- name: authorize root splice for satellite
  hosts:
  - SATELLITE
  user: root

  vars_files:
  - splice/vars/sst_ssh_keys.yml

  tasks:
  - include: common/ssh_authorize_key.yml 
