# setup a SAM node
- name: setup sam node
  hosts:
  - SAM
  user: root

  vars_files:
  - splice/vars/iso.yml

  tasks:
  # copy and mount the sam iso
  - include: common/iso.yml

  # - include: common/mongodb.yml
  - include: splice/install.yml
  - include: splice/checkin_configure.yml

  # configure firewall
  - include: common/iptables_ports.yml
    vars:
      open_ports:
      - 443
      - 8088

- name: ssh_keygen for splice root
  hosts:
  - SAM
  user: root
  sudo: yes
  sudo_user: splice

  vars_files:
  - splice/vars/sst_ssh_keys.yml

  tasks:
  - include: common/ssh_keygen.yml


- name: create swreport@master user for fake sst
  connection: local
  user: root
  hosts:
  - Master

  tasks:
  - name: create swreport@master user for fake sst
    action: user name=swreport  generate_ssh_key=yes

- name: authorize splice@katello to swreport@master for fake sst
  connection: local 
  user: root
  hosts:
  - Master

  vars_files:
  - splice/vars/sst_ssh_keys.yml

  tasks:
  - include: common/ssh_authorize_key.yml
    vars:
      ssh_authorized_keys_user: swreport

- name: disable sst cron jobs to prevent messing with test cases
  hosts:
  - SAM

  tasks:
  - name: disable sst cron jobs
    action: shell sed -i 's,^[^#],#&,' ${item}
    with_items:
    - /etc/cron.d/splice-sst-sync
    - /etc/cron.d/spacewalk-sst-sync

  - name: reload crond service
    action: service 
      name=crond
      state=reloaded
  

- name: configure splicetestlib
  connection: local 
  hosts:
  - Master
  user: root

  tasks:
  # configure sam user and password
  - name: propagate sam user to splicetestlib
    action: shell splice-add-testing-parameter.py --param=katello_user --value=admin
    tags:
    - splice
    - sam
    - splicetestlib
    - configuration

  - name: propagate sam password to splicetestlib
    action: shell splice-add-testing-parameter.py --param=katello_password --value=${item}
    with_file: /etc/katello_password
    tags:
    - splice
    - sam
    - splicetestlib
    - connection
