# provide answers file for splice:install.pl
# requires rhn.user, rhn.password, rhn.sysname vars
- name: satellite install answers file
  action: template
    src=satellite/templates/answers.j2
    dest=${answers.file}
    owner=root
    group=root
  when: "answers.file is defined"
  when: "rhn.user is defined"
  when: "rhn.password is defined"
  when: "rhn.sysname is defined"
  when: "rhn.cert is defined"
  tags:
  - satellite_answers

- name: copy satellite cert
  action: copy
    src=${credentials.rhn_cert}
    dest=${credentials.rhn_cert}
    owner=${credentials.owner}
    group=${credentials.group}
    mode=${credentials.mode}
  when: "credentials.rhn_cert is defined"
  when: "credentials.path is defined"
  when: "credentials.owner is defined"
  when: "credentials.group is defined"
  when: "credentials.mode is defined"
  tags:
  - credentials
  - credentials_copy_cert


