# satellite credentials to be set on Master

# copy satellite cert to master
- name: copy satellite cert
  action: copy
    src=${credentials.rhn_cert}
    dest=${credentials.rhn_cert}
    owner=${credentials.owner}
    group=${credentials.group}
    mode=${credentials.mode}
  when: "credentials.rhn_cert is defined"
  when: "credentials.path is defined"
  when: "credentials.owner is defined"
  when: "credentials.group is defined"
  when: "credentials.mode is defined"
  tags:
  - credentials
  - credentials_copy_cert

# answers.yml reuses these as variables input
- name: satellite master credentials template
  action: template
    src=satellite/templates/credentials.j2
    dest=${credentials.path}
    owner=${credentials.owner}
    group=${credentials.group}
    mode=${credentials.mode}
  when: "credentials.rhn_user is defined"
  when: "credentials.rhn_password is defined"
  when: "credentials.rhn_system_name is defined"
  when: "credentials.rhn_cert is defined"
  when: "credentials.path is defined"
  when: "credentials.owner is defined"
  when: "credentials.group is defined"
  when: "credentials.mode is defined"
  tags:
  - credentials
  - credentials_template
