# handle splice spcecific master repos
- name: fork splice master repos
  action: git
    repo=${item.url}
    dest=/usr/src/${item.name}
    version=${item.version}
  tags:
  - splice_master_repos
  with_items:
  - {name: python-patchwork, url: "https://github.com/RedHatQE/python-patchwork.git", version: HEAD}
  - {name: python-moncov, url: "https://github.com/RedHatQE/python-moncov.git", version: HEAD}
  - {name: splice-testing-tools, url: "https://github.com/RedHatQE/splice-testing-tools.git", version: HEAD}

- name: install splice tools from repos
  action: shell tito build --test --rpm --install
    chdir=/usr/src/${item}
  with_items:
  - python-patchwork
  - python-moncov
  - rhui-testing-tools
  tags:
  - splice_master_repos
  - install_splice_tools

